name: Bandit
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '34 18 * * 5'

permissions:
  contents: read

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Bandit scan
        run: |
          bandit -c pyproject.toml -r horrorvibes run.py scripts
